/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package payroll.system;

import java.awt.*;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Acer
 */

public class EmployeeManagement extends javax.swing.JFrame {

    Connection conn =null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    String username;
    
    Calendar cal = new GregorianCalendar();
    SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
    String date = sdf.format(cal.getTime());

    int second = cal.get(Calendar.SECOND);
    int minute = cal.get(Calendar.MINUTE);
    int hour = cal.get(Calendar.HOUR);
    DecimalFormat df = new DecimalFormat("00");
    String time = df.format(hour) + ":" + df.format(minute) + ":" + df.format(second);

    String type = "Employee Management";
    /**
     * Creates new form AddEmployee
     */
    public EmployeeManagement() {
        initComponents();
        conn= db.java_db();

    }
    public EmployeeManagement(String name) {
        this.username = name;
        
        initComponents();
        conn= db.java_db();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        main_panel = new javax.swing.JPanel();
        greeting_label2 = new javax.swing.JLabel();
        search_label = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        logout_button = new javax.swing.JButton();
        management_panel = new javax.swing.JPanel();
        EmployeeID = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        Gender = new javax.swing.JLabel();
        IC = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        txt_age = new javax.swing.JTextField();
        txt_IC = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        txt_email = new javax.swing.JTextField();
        Phoneno = new javax.swing.JLabel();
        r_male = new javax.swing.JRadioButton();
        r_female = new javax.swing.JRadioButton();
        txt_phoneno = new javax.swing.JTextField();
        Position = new javax.swing.JLabel();
        Department = new javax.swing.JLabel();
        BasicSalary = new javax.swing.JLabel();
        Epfid = new javax.swing.JLabel();
        Soscoid = new javax.swing.JLabel();
        Eisid = new javax.swing.JLabel();
        Lhdnid = new javax.swing.JLabel();
        txt_position = new javax.swing.JTextField();
        txt_department = new javax.swing.JTextField();
        txt_basicSalary = new javax.swing.JTextField();
        txt_epfid = new javax.swing.JTextField();
        txt_sosco = new javax.swing.JTextField();
        txt_eis = new javax.swing.JTextField();
        txt_lhdn = new javax.swing.JTextField();
        Update = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        AddEmployeeButton = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        img = new javax.swing.JLabel();
        Attach = new javax.swing.JButton();
        lab2 = new javax.swing.JLabel();
        lab4 = new javax.swing.JLabel();
        lab6 = new javax.swing.JLabel();
        lab5 = new javax.swing.JLabel();
        lab1 = new javax.swing.JLabel();
        lab3 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        side_menu = new javax.swing.JPanel();
        calculation_button = new javax.swing.JButton();
        slip_button = new javax.swing.JButton();
        dashboard_button1 = new javax.swing.JButton();
        employee_button = new javax.swing.JButton();
        logo = new javax.swing.JLabel();
        hr_label = new javax.swing.JLabel();
        payroll_label1 = new javax.swing.JLabel();
        system_label = new javax.swing.JLabel();
        audit_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main_panel.setBackground(new java.awt.Color(255, 255, 255));
        main_panel.setFocusable(false);
        main_panel.setFont(new java.awt.Font("Californian FB", 0, 14)); // NOI18N

        greeting_label2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        greeting_label2.setText("Employee Management");

        search_label.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        search_label.setText("Search Employee ID:");

        txt_search.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_searchActionPerformed(evt);
            }
        });
        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        logout_button.setBackground(new java.awt.Color(250, 255, 255));
        logout_button.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        logout_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/system/images/logout_icon.png"))); // NOI18N
        logout_button.setText("Logout");
        logout_button.setIconTextGap(12);
        logout_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_buttonActionPerformed(evt);
            }
        });

        management_panel.setBackground(new java.awt.Color(239, 242, 242));

        EmployeeID.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        EmployeeID.setText("Employee ID :");

        Name.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Name.setText("Name :");

        txt_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        txt_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nameKeyReleased(evt);
            }
        });

        txt_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_id.setSelectionColor(new java.awt.Color(0, 0, 0));
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_idKeyReleased(evt);
            }
        });

        Gender.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Gender.setText("Gender :");

        IC.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        IC.setText("IC :");

        Age.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Age.setText("Age :");

        txt_age.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ageActionPerformed(evt);
            }
        });
        txt_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_ageKeyReleased(evt);
            }
        });

        txt_IC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_IC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ICActionPerformed(evt);
            }
        });
        txt_IC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_ICKeyReleased(evt);
            }
        });

        Email.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Email.setText("Email :");

        txt_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_emailKeyReleased(evt);
            }
        });

        Phoneno.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Phoneno.setText("Phone Number :");

        r_male.setText("MALE");
        r_male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_maleActionPerformed(evt);
            }
        });

        r_female.setText("FEMALE");
        r_female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                r_femaleActionPerformed(evt);
            }
        });

        txt_phoneno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_phoneno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_phonenoActionPerformed(evt);
            }
        });
        txt_phoneno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_phonenoKeyReleased(evt);
            }
        });

        Position.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Position.setText("Position :");

        Department.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Department.setText("Department:");

        BasicSalary.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        BasicSalary.setText("Basic Salary :");

        Epfid.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Epfid.setText("EPF ID :");

        Soscoid.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Soscoid.setText("SOSCO ID :");

        Eisid.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Eisid.setText("EIS ID :");

        Lhdnid.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        Lhdnid.setText("LHDN ID :");

        txt_position.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_position.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_positionActionPerformed(evt);
            }
        });

        txt_department.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_department.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_departmentActionPerformed(evt);
            }
        });

        txt_basicSalary.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_epfid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_sosco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_eis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_lhdn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Update.setBackground(new java.awt.Color(250, 255, 255));
        Update.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/system/images/update_icon.png"))); // NOI18N
        Update.setText("Update");
        Update.setIconTextGap(6);
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(250, 255, 255));
        Delete.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/system/images/delete_icon.png"))); // NOI18N
        Delete.setText("Delete Employee");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        ClearButton.setBackground(new java.awt.Color(250, 255, 255));
        ClearButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ClearButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/system/images/clear_icon.png"))); // NOI18N
        ClearButton.setText("Clear");
        ClearButton.setIconTextGap(12);
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        AddEmployeeButton.setBackground(new java.awt.Color(250, 255, 255));
        AddEmployeeButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        AddEmployeeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/system/images/add_icon.png"))); // NOI18N
        AddEmployeeButton.setText("Add Employee");
        AddEmployeeButton.setIconTextGap(10);
        AddEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddEmployeeButtonActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(img, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(img, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addContainerGap())
        );

        Attach.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Attach.setText("Attach Photo");
        Attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttachActionPerformed(evt);
            }
        });

        lab2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lab2.setForeground(new java.awt.Color(204, 0, 0));

        lab4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lab4.setForeground(new java.awt.Color(204, 0, 0));
        lab4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lab4KeyReleased(evt);
            }
        });

        lab6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lab6.setForeground(new java.awt.Color(204, 0, 0));

        lab5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lab5.setForeground(new java.awt.Color(204, 0, 0));

        lab1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lab1.setForeground(new java.awt.Color(204, 0, 0));

        lab3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lab3.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout management_panelLayout = new javax.swing.GroupLayout(management_panel);
        management_panel.setLayout(management_panelLayout);
        management_panelLayout.setHorizontalGroup(
            management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(management_panelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(management_panelLayout.createSequentialGroup()
                        .addComponent(EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(management_panelLayout.createSequentialGroup()
                        .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(management_panelLayout.createSequentialGroup()
                                .addComponent(Phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(txt_phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lab6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(management_panelLayout.createSequentialGroup()
                                .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(management_panelLayout.createSequentialGroup()
                                        .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Name, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(IC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Gender, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Age, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Email, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(16, 16, 16))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, management_panelLayout.createSequentialGroup()
                                        .addComponent(Attach)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(management_panelLayout.createSequentialGroup()
                                        .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lab2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(management_panelLayout.createSequentialGroup()
                                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lab5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(management_panelLayout.createSequentialGroup()
                                        .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lab4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(management_panelLayout.createSequentialGroup()
                                        .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, management_panelLayout.createSequentialGroup()
                                                .addComponent(r_male, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27)
                                                .addComponent(r_female, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addComponent(txt_IC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lab3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, management_panelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, management_panelLayout.createSequentialGroup()
                                        .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(AddEmployeeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(10, 10, 10)
                                        .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(Update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(management_panelLayout.createSequentialGroup()
                                            .addComponent(Soscoid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(10, 10, 10)
                                            .addComponent(txt_sosco, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(management_panelLayout.createSequentialGroup()
                                            .addComponent(Eisid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(10, 10, 10)
                                            .addComponent(txt_eis, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(management_panelLayout.createSequentialGroup()
                                            .addComponent(Lhdnid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(10, 10, 10)
                                            .addComponent(txt_lhdn, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(management_panelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(management_panelLayout.createSequentialGroup()
                                        .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(management_panelLayout.createSequentialGroup()
                                                .addGap(4, 4, 4)
                                                .addComponent(Epfid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(BasicSalary, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                                        .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_epfid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_basicSalary, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(management_panelLayout.createSequentialGroup()
                                        .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Position, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_department, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_position, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        management_panelLayout.setVerticalGroup(
            management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(management_panelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lab1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_position, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Position, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(management_panelLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_sosco, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Soscoid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lab4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_eis, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Eisid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_lhdn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Lhdnid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(management_panelLayout.createSequentialGroup()
                        .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lab2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(management_panelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Department, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_department, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10)
                        .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(r_male)
                            .addComponent(r_female)
                            .addComponent(BasicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_basicSalary, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(management_panelLayout.createSequentialGroup()
                                .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(IC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_IC, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lab3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lab5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lab6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Epfid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_epfid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(management_panelLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddEmployeeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(management_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(management_panelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Attach, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        back.setFont(new java.awt.Font("Californian FB", 1, 36)); // NOI18N
        back.setText("<");
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout main_panelLayout = new javax.swing.GroupLayout(main_panel);
        main_panel.setLayout(main_panelLayout);
        main_panelLayout.setHorizontalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(greeting_label2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                        .addComponent(logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(main_panelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(search_label)
                        .addGap(20, 20, 20)
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(management_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        main_panelLayout.setVerticalGroup(
            main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(main_panelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(greeting_label2)
                        .addComponent(back))
                    .addComponent(logout_button, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(main_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(search_label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(management_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );

        side_menu.setBackground(new java.awt.Color(0, 33, 120));
        side_menu.setPreferredSize(new java.awt.Dimension(226, 550));

        calculation_button.setBackground(new java.awt.Color(0, 30, 120));
        calculation_button.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        calculation_button.setForeground(new java.awt.Color(255, 255, 255));
        calculation_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/system/images/calculation_icon.png"))); // NOI18N
        calculation_button.setText("Salary Calculation");
        calculation_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        calculation_button.setIconTextGap(23);
        calculation_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculation_buttonActionPerformed(evt);
            }
        });

        slip_button.setBackground(new java.awt.Color(0, 30, 120));
        slip_button.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        slip_button.setForeground(new java.awt.Color(255, 255, 255));
        slip_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/system/images/slip_icon.png"))); // NOI18N
        slip_button.setText("Salary Slip");
        slip_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        slip_button.setIconTextGap(38);
        slip_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slip_buttonActionPerformed(evt);
            }
        });

        dashboard_button1.setBackground(new java.awt.Color(0, 30, 120));
        dashboard_button1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        dashboard_button1.setForeground(new java.awt.Color(255, 255, 255));
        dashboard_button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/system/images/dashboard_icon.png"))); // NOI18N
        dashboard_button1.setText("Dashboard");
        dashboard_button1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboard_button1.setIconTextGap(40);
        dashboard_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboard_button1ActionPerformed(evt);
            }
        });

        employee_button.setBackground(new java.awt.Color(250, 255, 255));
        employee_button.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        employee_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/system/images/empmanagement_icon.png"))); // NOI18N
        employee_button.setText(" Employee Management");
        employee_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        employee_button.setIconTextGap(5);
        employee_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employee_buttonActionPerformed(evt);
            }
        });

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/system/images/logo1.png"))); // NOI18N
        logo.setPreferredSize(new java.awt.Dimension(100, 130));

        hr_label.setFont(new java.awt.Font("Californian FB", 0, 32)); // NOI18N
        hr_label.setForeground(new java.awt.Color(255, 255, 255));
        hr_label.setText("HR &");

        payroll_label1.setFont(new java.awt.Font("Californian FB", 0, 32)); // NOI18N
        payroll_label1.setForeground(new java.awt.Color(255, 255, 255));
        payroll_label1.setText("Payroll");

        system_label.setFont(new java.awt.Font("Californian FB", 0, 32)); // NOI18N
        system_label.setForeground(new java.awt.Color(255, 255, 255));
        system_label.setText("System");

        audit_button.setBackground(new java.awt.Color(0, 30, 120));
        audit_button.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        audit_button.setForeground(new java.awt.Color(255, 255, 255));
        audit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/system/images/history_icon.png"))); // NOI18N
        audit_button.setText("Audit Trail");
        audit_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        audit_button.setIconTextGap(50);
        audit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                audit_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout side_menuLayout = new javax.swing.GroupLayout(side_menu);
        side_menu.setLayout(side_menuLayout);
        side_menuLayout.setHorizontalGroup(
            side_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_menuLayout.createSequentialGroup()
                .addGroup(side_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(side_menuLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(side_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(slip_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(calculation_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dashboard_button1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(employee_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(audit_button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(side_menuLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(side_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hr_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(payroll_label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(system_label, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        side_menuLayout.setVerticalGroup(
            side_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(side_menuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(side_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, side_menuLayout.createSequentialGroup()
                        .addComponent(hr_label)
                        .addGap(1, 1, 1)
                        .addComponent(payroll_label1)
                        .addGap(1, 1, 1)
                        .addComponent(system_label))
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(dashboard_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(employee_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(calculation_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(slip_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(audit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(side_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(main_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(side_menu, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1200, 680));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void calculation_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculation_buttonActionPerformed
        // TODO add your handling code here:
        SalaryCalculation c = new SalaryCalculation(username);
        c.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_calculation_buttonActionPerformed

    private void slip_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slip_buttonActionPerformed
        // TODO add your handling code here:
        SalarySlip s = new SalarySlip(username);
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_slip_buttonActionPerformed

  
    private void dashboard_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboard_button1ActionPerformed
        // TODO add your handling code here:
        Homepage x = new Homepage();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dashboard_button1ActionPerformed

    private void employee_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employee_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employee_buttonActionPerformed

    private void txt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        // TODO add your handling code here:

        try{
            
            String searchTerm = txt_search.getText();
            
             if (!searchTerm.isEmpty()) {
            
            String sql ="select * from Employee where employee_id=? ";

            pst=conn.prepareStatement(sql);
            pst.setString(1,txt_search.getText());
            rs=pst.executeQuery();
            
            if (rs.next()) {
            String add1 =rs.getString("employee_id");
            txt_id.setText(add1);

            String add2 =rs.getString("employee_name");
            txt_name.setText(add2);
            
            String genderValue = rs.getString("employee_gender");
            if ("MALE".equals(genderValue)) {
                r_male.setSelected(true);
                r_female.setSelected(false);    
            } else if ("FEMALE".equals(genderValue)) {
                r_male.setSelected(false);
                r_female.setSelected(true);
            } else {
                r_male.setSelected(false);
                r_female.setSelected(false);
            }

            String add3 =rs.getString("employee_ic");
            txt_IC.setText(add3);

            String add4 =rs.getString("employee_age");
            txt_age.setText(add4);

            String add5 =rs.getString("employee_email");
            txt_email.setText(add5);

            String add6 =rs.getString("employee_phone_number");
            txt_phoneno.setText(add6);

            String add7 =rs.getString("employee_position");
            txt_position.setText(add7);

            String add8 =rs.getString("employee_department");
            txt_position.setText(add8);

            String add9 =rs.getString("employee_basic_salary");
            txt_basicSalary.setText(add9);

            String add10 =rs.getString("employee_epf_id");
            txt_epfid.setText(add10);

            String add11 =rs.getString("employee_sosco_id");
            txt_sosco.setText(add11);

            String add12 =rs.getString("employee_eis_id");
            txt_eis.setText(add12);

            String add13 =rs.getString("employee_lhdn_id");
            txt_lhdn.setText(add13);
            
            byte[] imageData = rs.getBytes("employee_image");
             if (imageData != null) {
            ImageIcon imageIcon = new ImageIcon(imageData);
            Image image = imageIcon.getImage();

    
            Image scaledImage = image.getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_SMOOTH);
    
    
            ImageIcon scaledImageIcon = new ImageIcon(scaledImage);


            img.setIcon(scaledImageIcon);
                } else {
                    img.setIcon(null);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Employee with ID " + searchTerm + " not found. You may add the employee.");
                String id = txt_search.getText();
                txt_id.setText(id);
            }
        } else {
        }
        } catch(SQLException e){
             JOptionPane.showMessageDialog(null, "Error searching for employee: " + e.getMessage());
        }
        finally {
                try {
                    if (rs != null) {
                        rs.close();
                    }
                    if (pst != null) {
                        pst.close();
                    }
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e);
                }
        }
    }//GEN-LAST:event_txt_searchKeyReleased

    private void logout_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_buttonActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showOptionDialog(
            this,
            "Are you sure you want to logout?",
            "Confirm Logout",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            new Object[]{"Logout", "Cancel"},
            "Logout"
        );

        if (option == JOptionPane.YES_OPTION) {
            Login x = new Login();
            x.setVisible(true);
            this.dispose();
            
            String action = "Logout as " + username;
            String auditSQL = "INSERT INTO Audit (audit_date, audit_time, audit_type, audit_action) VALUES (?,?,?,?)";
            try {
                pst = conn.prepareStatement(auditSQL);
                pst.setString(1, date);
                pst.setString(2, time);
                pst.setString(3, "Login & Logout");
                pst.setString(4, action);
                pst.executeUpdate();
            } catch (SQLException ex) {
                Logger.getLogger(Homepage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_logout_buttonActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void txt_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nameKeyReleased
        // TODO add your handling code here:
        String nameText = txt_name.getText().trim();

        if (!nameText.isEmpty()) {

            if (nameText.matches("^[a-zA-Z ]+$")) {
                lab2.setText(null);  // Valid name, clear error message
            } else {
                lab2.setText("Invalid name");
                lab2.setForeground(Color.RED);
            }
        }
    }//GEN-LAST:event_txt_nameKeyReleased

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void txt_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyReleased
        // TODO add your handling code here:
        String idText = txt_id.getText().trim();

        if (!idText.isEmpty()) {

                Double id = Double.valueOf(idText);

                // Check if the ID contains only digits
                if (idText.matches("^\\d+$")) 
                {
                    lab1.setText(null);
                } else {
                    lab1.setText("Invalid ID");
                    lab1.setForeground(Color.RED);
                   }
               }
        
        
    }//GEN-LAST:event_txt_idKeyReleased

    private void txt_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ageActionPerformed

    private void txt_ageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ageKeyReleased
        // TODO add your handling code here:
        String ageText = txt_age.getText().trim();

        if (!ageText.isEmpty()) {
            try {
                int age = Integer.parseInt(ageText);

                if (age >= 0) {
                    lab4.setText(null);  // Valid age, clear error message
                } else {
                    lab4.setText("Invalid Age");
                    lab4.setForeground(Color.RED);
                }
            } catch (NumberFormatException e) {
                lab4.setText("Invalid Age");
                lab4.setForeground(Color.RED);
            }
        }else
        {
             lab4.setText(null);
        }
    }//GEN-LAST:event_txt_ageKeyReleased

    private void txt_ICKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ICKeyReleased
        // TODO add your handling code here:
        String icText = txt_IC.getText().trim();

        if (!icText.isEmpty()) {
            if (icText.matches("^\\d{12}$")) {
                lab3.setText(null);  // Valid IC, clear error message
                
                int currentYear = cal.get(Calendar.YEAR);
                String ic = txt_IC.getText();
                char firstDigitChar = ic.charAt(0);
                char secondDigitChar = ic.charAt(1);
                int firstDigit = Character.getNumericValue(firstDigitChar);
                int secondDigit = Character.getNumericValue(secondDigitChar);

                int birthYear;
                if(firstDigit > 2)
                    birthYear = 1900 + (firstDigit*10) + secondDigit;
                else
                    birthYear = 2000 + (firstDigit*10) + secondDigit;

                int age = currentYear - birthYear;
                txt_age.setText(Integer.toString(age));
            } else {
                lab3.setText("Invalid IC");
                lab3.setForeground(Color.RED);
            }
        }else 
         { lab3.setText(null);
         }

    }//GEN-LAST:event_txt_ICKeyReleased

    private void txt_emailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyReleased
        // TODO add your handling code here:
        String emailText = txt_email.getText().trim();

        if (!emailText.isEmpty()) {
            if (emailText.matches(".+@.+\\.com")) {
                lab5.setText(null);  // Valid email, clear error message
            } else {
                lab5.setText("Invalid email");
                lab5.setForeground(Color.RED);
            }
             }
              else{
              lab5.setText(null); 
        }
    }//GEN-LAST:event_txt_emailKeyReleased

    private void r_maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_maleActionPerformed
        // TODO add your handling code here:

        gender = "MALE";
        r_male.setSelected(true);
        r_female.setSelected(false);
       
    }//GEN-LAST:event_r_maleActionPerformed

    private void r_femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_r_femaleActionPerformed
        // TODO add your handling code here:
        gender = "FEMALE";
        r_female.setSelected(true);
        r_male.setSelected(false);
    
    }//GEN-LAST:event_r_femaleActionPerformed

    private void txt_phonenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_phonenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_phonenoActionPerformed

    private void txt_phonenoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_phonenoKeyReleased
        // TODO add your handling code here:
        String phoneText = txt_phoneno.getText().trim();

        if (!phoneText.isEmpty()) {
            // Check if the phone number contains only digits
            if (phoneText.matches("\\d+")) {
                lab6.setText(null);  // Valid phone number, clear error message
            } else {
                lab6.setText("Invalid No");
                lab6.setForeground(Color.RED);
            }
        }else{
           lab6.setText(null);
        }

    }//GEN-LAST:event_txt_phonenoKeyReleased

    private void txt_positionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_positionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_positionActionPerformed

    private void txt_departmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_departmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_departmentActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:

        try {
            String val = txt_id.getText();
            String val2 = txt_name.getText();
            String val4 = txt_IC.getText();
            String val5 = txt_age.getText();
            String val6 = txt_email.getText();
            String val7 = txt_phoneno.getText();
            String val8 = txt_position.getText();
            String val9 = txt_department.getText();
            String val10 = txt_basicSalary.getText();
            String val11 = txt_epfid.getText();
            String val12 = txt_sosco.getText();
            String val13 = txt_eis.getText();
            String val14 = txt_lhdn.getText();

            // Determine the selected gender based on radio buttons
            String gender = "";
            if (r_male.isSelected()) {
                gender = "MALE";
            } else if (r_female.isSelected()) {
                gender = "FEMALE";
            }

            String sql = "UPDATE Employee SET employee_name=?, "
            + "employee_ic=?, employee_age=?, employee_email=?, "
            + "employee_phone_number=?, employee_position=?, employee_department=?, "
            + "employee_basic_salary=?, employee_epf_id=?, employee_sosco_id=?, "
            + "employee_eis_id=?, employee_lhdn_id=?, employee_gender=?, employee_image=? "
            + "WHERE employee_id=?";

            if (employee_image != null) {
                pst = conn.prepareStatement(sql);
                pst.setString(1, val2);
                pst.setString(2, val4);
                pst.setString(3, val5);
                pst.setString(4, val6);
                pst.setString(5, val7);
                pst.setString(6, val8);
                pst.setString(7, val9);
                pst.setString(8, val10);
                pst.setString(9, val11);
                pst.setString(10, val12);
                pst.setString(11, val13);
                

                pst.setString(12, val14);
                pst.setString(13, gender);
                pst.setBytes(14,employee_image);
                pst.setString(15, val);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(null, "Record Updated");
                
                String employee = txt_id.getText();
                String action = "Update data for employee id: " + employee;
                String auditSQL = "INSERT INTO Audit (audit_date, audit_time, audit_type, audit_action) VALUES (?,?,?,?)";
                pst = conn.prepareStatement(auditSQL);
                pst.setString(1, date);
                pst.setString(2, time);
                pst.setString(3, type);
                pst.setString(4, action);
                pst.executeUpdate();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error updating record: ");
        } finally {
            try {
                rs.close();
                pst.close();
            } catch (SQLException e) {
                // Handle the exception
            }
        }
    }//GEN-LAST:event_UpdateActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:

        try{
            String employee = txt_id.getText();
            String sqlEmployee ="delete from Employee where employee_id=? ";
            pst=conn.prepareStatement(sqlEmployee);
            pst.setString(1, txt_id.getText());
            pst.execute();
            
            String sqlSalary ="delete from Salary where emp_id=? ";
            pst=conn.prepareStatement(sqlSalary);
            pst.setString(1, txt_id.getText());
            pst.execute();

            JOptionPane.showMessageDialog(null,"Record Deleted");
            txt_id.setText("");
            txt_name.setText("");
            txt_IC.setText("");
            txt_age.setText("");
            txt_email.setText("");
            txt_phoneno.setText("");
            txt_position.setText("");
            txt_department.setText("");
            txt_basicSalary.setText("");
            txt_epfid.setText("");
            txt_sosco.setText("");
            txt_eis.setText("");
            txt_lhdn.setText("");
            r_male.setSelected(false);
            r_female.setSelected(false);
            img.setIcon(null);
            employee_image=null;
            
            String action = "Delete data for employee id: " + employee;
            String auditSQL = "INSERT INTO Audit (audit_date, audit_time, audit_type, audit_action) VALUES (?,?,?,?)";
            pst = conn.prepareStatement(auditSQL);
            pst.setString(1, date);
            pst.setString(2, time);
            pst.setString(3, type);
            pst.setString(4, action);
            pst.executeUpdate();
            

        }catch(SQLException e){

            JOptionPane.showMessageDialog(null, e);
        }finally {

            try{
                rs.close();
                pst.close();

            }
            catch(SQLException e){

            }

        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        // TODO add your handling code here:

        txt_search.setText("");
        txt_id.setText("");
        txt_name.setText("");
        txt_IC.setText("");
        txt_age.setText("");
        txt_email.setText("");
        txt_phoneno.setText("");
        txt_position.setText("");
        txt_department.setText("");
        txt_basicSalary.setText("");
        txt_epfid.setText("");
        txt_sosco.setText("");
        txt_eis.setText("");
        txt_lhdn.setText("");
        r_male.setSelected(false);
        r_female.setSelected(false);
        img.setIcon(null);
        employee_image=null;

    }//GEN-LAST:event_ClearButtonActionPerformed

    private void AddEmployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddEmployeeButtonActionPerformed
        // TODO add your handling code here:

        try {

            String sql ="insert into Employee "
            + "(employee_id,employee_name,employee_gender,employee_ic,"
            + "employee_age,employee_email,employee_phone_number,"
            + "employee_position,employee_department,employee_basic_salary,"
            + "employee_epf_id,employee_sosco_id,employee_eis_id,employee_lhdn_id,employee_image)values (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

            pst=conn.prepareStatement(sql);
            pst.setString(1, txt_id.getText());
            pst.setString(2, txt_name.getText());
            pst.setString(3, gender);
            pst.setString(4, txt_IC.getText());
            pst.setString(5, txt_age.getText());
            pst.setString(6, txt_email.getText());
            pst.setString(7, txt_phoneno.getText());
            pst.setString(8, txt_position.getText());
            pst.setString(9, txt_department.getText());
            pst.setString(10, txt_basicSalary.getText());
            pst.setString(11, txt_epfid.getText());
            pst.setString(12, txt_sosco.getText());
            pst.setString(13, txt_eis.getText());
            pst.setString(14, txt_lhdn.getText());
            pst.setBytes(15, employee_image);

            pst.execute();
            JOptionPane.showMessageDialog(null,"Data is saved successfully");
            
            String employee = txt_id.getText();
            String action = "Add data for employee id: " + employee;
            String auditSQL = "INSERT INTO Audit (audit_date, audit_time, audit_type, audit_action) VALUES (?,?,?,?)";
            pst = conn.prepareStatement(auditSQL);
            pst.setString(1, date);
            pst.setString(2, time);
            pst.setString(3, type);
            pst.setString(4, action);
            pst.executeUpdate();

        }
        catch (SQLException e)

        {
            JOptionPane.showMessageDialog(null, "Error saving data: " +e.getMessage());
        }

        finally {

            try{
                rs.close();
                pst.close();

            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Error closing resources: ");
            }

        }
    }//GEN-LAST:event_AddEmployeeButtonActionPerformed

    private void AttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttachActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();

        filename = f.getAbsolutePath();
        ImageIcon imageIcon = new ImageIcon (new ImageIcon(filename).getImage().getScaledInstance(img.getWidth(), img.getHeight(), Image.SCALE_DEFAULT));
        img.setIcon(imageIcon);

        try{
            File image = new File(filename);
            FileInputStream fix = new FileInputStream(image);
            ByteArrayOutputStream bos = new ByteArrayOutputStream();
            byte[] buf = new byte[1024];

            for (int number;(number = fix.read(buf)) != -1;){
                bos.write(buf,0,number);
            }
            employee_image = bos.toByteArray();

        }catch (FileNotFoundException e) {
            JOptionPane.showMessageDialog(null, "File not found: " + filename);

        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "Error reading file: ");

        }
    }//GEN-LAST:event_AttachActionPerformed

    private void lab4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lab4KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lab4KeyReleased

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        // TODO add your handling code here:
        Homepage h = new Homepage();
        h.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void audit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_audit_buttonActionPerformed
        // TODO add your handling code here:
        Audit a = new Audit(username);
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_audit_buttonActionPerformed

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void txt_ICActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ICActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ICActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddEmployeeButton;
    private javax.swing.JLabel Age;
    private javax.swing.JButton Attach;
    private javax.swing.JLabel BasicSalary;
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton Delete;
    private javax.swing.JLabel Department;
    private javax.swing.JLabel Eisid;
    private javax.swing.JLabel Email;
    private javax.swing.JLabel EmployeeID;
    private javax.swing.JLabel Epfid;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel IC;
    private javax.swing.JLabel Lhdnid;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Phoneno;
    private javax.swing.JLabel Position;
    private javax.swing.JLabel Soscoid;
    private javax.swing.JButton Update;
    private javax.swing.JButton audit_button;
    private javax.swing.JLabel back;
    private javax.swing.JButton calculation_button;
    private javax.swing.JButton dashboard_button1;
    private javax.swing.JButton employee_button;
    private javax.swing.JLabel greeting_label2;
    private javax.swing.JLabel hr_label;
    private javax.swing.JLabel img;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel lab1;
    private javax.swing.JLabel lab2;
    private javax.swing.JLabel lab3;
    private javax.swing.JLabel lab4;
    private javax.swing.JLabel lab5;
    private javax.swing.JLabel lab6;
    private javax.swing.JLabel logo;
    private javax.swing.JButton logout_button;
    private javax.swing.JPanel main_panel;
    private javax.swing.JPanel management_panel;
    private javax.swing.JLabel payroll_label1;
    private javax.swing.JRadioButton r_female;
    private javax.swing.JRadioButton r_male;
    private javax.swing.JLabel search_label;
    private javax.swing.JPanel side_menu;
    private javax.swing.JButton slip_button;
    private javax.swing.JLabel system_label;
    private javax.swing.JTextField txt_IC;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_basicSalary;
    private javax.swing.JTextField txt_department;
    private javax.swing.JTextField txt_eis;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_epfid;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_lhdn;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_phoneno;
    private javax.swing.JTextField txt_position;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txt_sosco;
    // End of variables declaration//GEN-END:variables

    private ImageIcon format = null;
    String filename = null;
    byte[] employee_image = null;
    
    private String gender;
}
