/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package payroll.system;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.awt.Font;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;

/**
 *
 * @author Acer
 */
public final class Login extends javax.swing.JFrame {
    Connection conn = null;
    ResultSet rs = null;
    PreparedStatement pst = null;
    /**
     * Creates new form Login
     */
    public Login() {
        
        initComponents();

        conn = db.java_db();
        currentDate();
    }
    
    private void currentDate(){
        Calendar cal = new GregorianCalendar();
        SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
        String date = sdf.format(cal.getTime());


        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);
        DecimalFormat df = new DecimalFormat("00");
        String time = df.format(hour) + ":" + df.format(minute) + ":" + df.format(second);
        
        date_menu.setText(date);
        time_menu.setText(time);
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        background = new javax.swing.JPanel();
        login_container = new javax.swing.JPanel();
        instruction = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        password_text = new javax.swing.JPasswordField();
        username_text = new javax.swing.JTextField();
        login_button = new javax.swing.JButton();
        login_image = new javax.swing.JLabel();
        menu_bar = new javax.swing.JMenuBar();
        date_menu = new javax.swing.JMenu();
        time_menu = new javax.swing.JMenu();

        jMenu3.setText("jMenu3");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 33, 120));
        setSize(new java.awt.Dimension(1200, 680));

        background.setBackground(new java.awt.Color(0, 33, 120));
        background.setPreferredSize(new java.awt.Dimension(500, 300));

        login_container.setBackground(new java.awt.Color(255, 255, 255));
        login_container.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        login_container.setPreferredSize(new java.awt.Dimension(300, 320));
        login_container.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        instruction.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        instruction.setText("Login with username and password");
        login_container.add(instruction, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));
        instruction.getAccessibleContext().setAccessibleDescription("");

        username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username.setText("Username:");
        username.setMaximumSize(new java.awt.Dimension(100, 40));
        login_container.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 100, -1));

        password.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        password.setText("Password:");
        login_container.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 100, -1));

        password_text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        password_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_textActionPerformed(evt);
            }
        });
        login_container.add(password_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 230, 30));

        username_text.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        username_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username_textActionPerformed(evt);
            }
        });
        login_container.add(username_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 230, 30));

        login_button.setBackground(new java.awt.Color(250, 255, 255));
        login_button.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        login_button.setText("Login");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        login_container.add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 150, 40));

        login_image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/payroll/system/images/login_background.png"))); // NOI18N

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(login_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(74, 74, 74)
                .addComponent(login_container, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(login_container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(148, 148, 148))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(login_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(55, 55, 55))
        );

        date_menu.setText("Date");
        menu_bar.add(date_menu);

        time_menu.setText("Edit");
        menu_bar.add(time_menu);

        setJMenuBar(menu_bar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 656, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1200, 680));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        // TODO add your handling code here:
        String sql = "select admin_username, admin_password from Admin where (admin_username =? and admin_password =?)";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, username_text.getText());
            char[] passwordChars = password_text.getPassword();
            String enteredPassword = new String(passwordChars);
            pst.setString(2, enteredPassword);

            rs = pst.executeQuery();
            if (rs.next()) {
                JOptionPane.showMessageDialog(null, "Login Successful");

                try {
                    Calendar cal = new GregorianCalendar();
                    SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
                    String date = sdf.format(cal.getTime());

                    int second = cal.get(Calendar.SECOND);
                    int minute = cal.get(Calendar.MINUTE);
                    int hour = cal.get(Calendar.HOUR);
                    String time = hour + ":" + minute + ":" + second;

                    String user = username_text.getText();
                    String type = "Login & Logout";
                    String action = "Login as " + user;

                    String auditSQL = "INSERT INTO Audit (audit_date, audit_time, audit_type, audit_action) VALUES (?,?,?,?)";
                    pst = conn.prepareStatement(auditSQL);
                    pst.setString(1, date);
                    pst.setString(2, time);
                    pst.setString(3, type);
                    pst.setString(4, action);

                    pst.executeUpdate();
                    
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, "Error saving data: " + e.getMessage());
                }

                // open homepage
                Homepage homepage = new Homepage(username_text.getText());
                homepage.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Username and password are incorrect.\n Please try again");

                // clear username and password fields
                username_text.setText("");
                password_text.setText("");
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                if (rs != null) {
                    rs.close();
                }
                if (pst != null) {
                    pst.close();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_login_buttonActionPerformed

    private void username_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username_textActionPerformed

    private void password_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_textActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JMenu date_menu;
    private javax.swing.JLabel instruction;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton login_button;
    private javax.swing.JPanel login_container;
    private javax.swing.JLabel login_image;
    private javax.swing.JMenuBar menu_bar;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField password_text;
    private javax.swing.JMenu time_menu;
    private javax.swing.JLabel username;
    private javax.swing.JTextField username_text;
    // End of variables declaration//GEN-END:variables
}
